implement Iterator in Session class
compwright/php-session pull request #11
Opened 2022-12-24 06:21 UTC by yani

Implemented `\Iterator` interface into `Session` class.  
The `\Iterator` interface is what makes `foreach()` work.   
Also added a testing scenario. 

Closes my own issue: https://github.com/compwright/php-session/issues/10

Still wondering if `Serializable` is worth implementing.

2022-12-24 15:22 UTC, compwright requested changes
Well done! Thanks for including the test case. We have some test failures, I think it's from the missing guard statements.

2022-12-24 15:22 UTC, compwright commented on src/Session.php
> +        reset($this->contents);
Should throw if not initialized. Should fix the test failure.

```suggestion
        if (!$this->isInitialized()) {
            throw new RuntimeException('Session not initialized');
        }
        
        reset($this->contents);
```

2022-12-24 15:22 UTC, compwright commented on src/Session.php
> +        return current($this->contents);
```suggestion
        if (!$this->isInitialized()) {
            throw new RuntimeException('Session not initialized');
        }
        
        return current($this->contents);
```

2022-12-24 15:22 UTC, compwright commented on src/Session.php
> +        return key($this->contents);
```suggestion
        if (!$this->isInitialized()) {
            throw new RuntimeException('Session not initialized');
        }
        
        return key($this->contents);
```

2022-12-24 15:22 UTC, compwright commented on src/Session.php
> +        next($this->contents);
```suggestion
        if (!$this->isInitialized()) {
            throw new RuntimeException('Session not initialized');
        }
        
        next($this->contents);
```

2022-12-24 15:22 UTC, compwright commented on src/Session.php
> +        return key($this->contents) !== null;
```suggestion
        if (!$this->isInitialized()) {
            throw new RuntimeException('Session not initialized');
        }
        
        return key($this->contents) !== null;
```

2022-12-24 15:24 UTC, compwright commented
We don't need Serializable, there's nothing in Session that would require special handling. It's only needed when serializing objects that contain things needing special handling like resources. We have a simple array, and so Session can be serialized just fine as-is.

2022-12-26 09:58 UTC, yani commented
```
Error: Parameter #1 $array of function reset expects array|object, array|null given.
Error: Parameter #1 $array of function current expects array|object, array|null given.
Error: Parameter #1 $array of function key expects array|object, array|null given.
Error: Parameter #1 $array of function next expects array|object, array|null given.
Error: Parameter #1 $array of function key expects array|object, array|null given.
```

Reason is `array|null` on `$contents`:
```
    /**
     * @var mixed[]|null
     */
    protected ?array $contents = null;
```

I think `array|object` doesn't break anything so I'll change it to this and adjust accordingly:
```
protected array $contents = [];
```

2022-12-26 10:07 UTC, yani commented
Another workaround might be to do it like this on iterator methods:
```
next($this->contents ?? []);
```
But I think it's obvious that isn't correct.

By using empty arrays instead of null, `isInitialized()` might be obsolete.

Should I keep the method, and use a property like: `protected bool $is_initialized = false;`?

That way no changes to the Manager need to be done as it uses the method to determine whether or not to open the Session.  I'm wondering if the Manager **always** opens the Session regardless of flow. If so, it would be better to remove the method.

2022-12-27 14:58 UTC, compwright commented
> I think `array|object` doesn't break anything so I'll change it to this and adjust accordingly:
> 
> ```
> protected array $contents = [];
> ```

Let's not do that, it's uninitialized for a reason.



> ```
> Error: Parameter #1 $array of function key expects array|object, array|null given.
> ```
> 
> Reason is `array|null` on `$contents`

The guard statement will prevent acting on a null $contents, but PHPStan doesn't know that, so in this case I think it's fine to just add `// @phpstan-ignore-next-line` or whatever to suppress the error.

2022-12-28 10:45 UTC, yani commented
Updated tests as well

```
  Scenario: Iterate over populated session # features\access.feature:30
    When data exists                       # Compwright\PhpSession\BehaviorTest\AccessContext::dataExists()
    Then data is iterated                  # Compwright\PhpSession\BehaviorTest\AccessContext::iteratorSucceeds()

  Scenario: Iterate over non-populated session # features\access.feature:33
    When data does not exist                   # Compwright\PhpSession\BehaviorTest\AccessContext::dataDoesNotExist()
    Then data is not iterated                  # Compwright\PhpSession\BehaviorTest\AccessContext::iteratorFails()
```

2022-12-28 14:17 UTC, compwright approved these changes

2022-12-28 14:17 UTC, merged