fix overloading behaviour
compwright/php-session pull request #14
Opened 2023-01-10 06:28 UTC by yani

This code:
```php
$session['a'][] = 'test';
```
Resulted in the following error:
```
Indirect modification of overloaded element of Compwright\PhpSession\Session has no effect
```

This PR makes the magic getter methods act as references. 

It will behave like a normal array then.

The reason I added `clone` in the read tests is because I think the original PHP error is thrown when the variable is actually being used instead of just being referenced. "Using" the variable with `clone` fixes the test. 

I think I understand everything correctly and fixed this.  You can see how the tests fail if you remove the reference tokens (`&`) from the methods.

2023-01-10 06:30 UTC, yani commented
Ok `clone` was probably not the right way to do this. Or the error needs to be surpressed. Will look into it right away.

(I only ran tests and not phpstan locally, my bad!)

2023-01-22 11:18 UTC, yani commented
@compwright have you looked into this?

2023-01-22 20:41 UTC, compwright requested changes
Please fix the `lint` errors.

On the clone statements, I don't see why they are needed. If they are, perhaps you meant to clone $this->session rather than $this->session->{var}.

2023-02-14 00:09 UTC, compwright requested changes
@yani tests continue to fail even after removing `clone`. Please fix the test failures, and I will be happy to merge this in.

2023-02-14 01:22 UTC, yani commented
Hi. Sorry for taking so much time. I might have some time tomorrow.

I'll have to look for a way to make sure it's tested correctly. I think the test case should just be that it doesn't throw an exception, which I think is correctly handled by PHPUnit which would just return false for the case if it does. I still have to look at any possible differences between using the dynamic property way of doing it.

2023-02-15 04:43 UTC, yani commented
Don't fully rely on the tests at the moment. 

This currently DOES NOT WORK outside of tests:
```
$session['foo'] ?? 'bar';
```
I'm looking into it.

2023-02-15 04:52 UTC, yani commented
I had to manually throw E_USER_NOTICE to keep current tests working but also implement the original overloading behavior.

I tested it on the project where I encountered the error and everything seems to be working as intended as far as I can tell.

2023-03-03 07:40 UTC, yani commented
@compwright I'm not sure if you're waiting for me to mark your change request as done. But I'm unable to mark it as such. 

If you're keeping this open because you don't like the E_USER_NOTICE, I could maybe try and figure out another way but I think this is as good as it gets.

2024-01-08 15:34 UTC, compwright approved these changes

2024-01-08 15:35 UTC, merged